In [7]:
from rasterio import open
from glob import glob
import numpy as np

In [8]:
path_to_images = "/data/spacenet/bldg/data/pytorch-PAN/images/"
image_files = glob(path_to_images + "/*.tif")
band_count = 1

In [9]:
file_band_means = np.zeros((len(image_files), band_count))
file_band_stds = np.zeros((len(image_files), band_count))
file_band_maxs = np.zeros((len(image_files), band_count))
file_band_mins = np.zeros((len(image_files), band_count))

In [10]:
for idx, image in enumerate(image_files):
    raster_file = open(image)
    for band_idx in range(raster_file.count):
        band = raster_file.read(band_idx + 1)
        band_mean = band.mean()
        band_std = band.std()
        band_max = band.max()
        band_min = band.min()
        file_band_means[idx, band_idx] = band_mean
        file_band_stds[idx, band_idx] = band_std
        file_band_maxs[idx, band_idx] = band_max
        file_band_mins[idx, band_idx] = band_min

In [11]:
global_mean = file_band_means.mean(axis=0)
global_std = file_band_stds.mean(axis=0)
global_max = file_band_stds.max(axis=0)
global_min = file_band_stds.min(axis=0)
res = np.stack((np.array(global_mean), np.array(global_std)), axis=0)
res = res.transpose()

In [12]:
res

array([[465.44523522, 166.47386568]])

In [14]:
global_max

array([756.03159495])

In [13]:
global_min

array([0.])

In [15]:
2**11

2048